"""Report contracts (PRD 8.12, 8.13, 13, 20).

The research report is where the one thing the system *generates* — the
narrative — finally appears. Everything about these models exists to keep that
generation honest:

* The **rating and every number live on the** :class:`~app.models.decision.InvestmentDecision`,
  which the report merely references. There is no rating field on
  :class:`ResearchReport` a narrative agent could write, so even a successful
  prompt injection cannot change the recommendation — it can only change the
  prose explaining it (PRD 6, 8.12).
* :class:`VerificationResult` records the adversarial check of that prose
  against the data layer, and it is carried *on the report* — a report that
  failed verification says so, prominently, rather than hiding it (PRD 8.13, E1).
* :func:`build_disclaimer` stamps the mandatory SEBI educational-use disclaimer
  on every report (PRD 20.2, C5).
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from app.models.decision import InvestmentDecision


class ReportSection(BaseModel):
    """One numbered section of the report (PRD 13.1)."""

    number: int
    title: str
    body: str = ""                       # markdown prose and/or tables
    subsections: list["ReportSection"] = Field(default_factory=list)


class WhatWouldChangeView(BaseModel):
    """Falsifiable upgrade/downgrade triggers (PRD 13.2) — analysis, not opinion."""

    upgrade_triggers: list[str] = Field(default_factory=list)
    downgrade_triggers: list[str] = Field(default_factory=list)
    monitorable_metrics: list[str] = Field(default_factory=list)


class InvestmentView(BaseModel):
    """The balanced view — including the bear case, stated fairly (PRD 20.3 E3)."""

    supports_rating: list[str] = Field(default_factory=list)
    argues_against: list[str] = Field(default_factory=list)
    bear_case: str = ""


class NumericIssue(BaseModel):
    """A number in the prose that could not be grounded in the data layer."""

    value: str
    context: str = ""


class VerificationResult(BaseModel):
    """Output of the Verifier (PRD 8.13)."""

    passed: bool
    attempts: int = 1
    numeric_claims_checked: int = 0
    unsupported_numbers: list[NumericIssue] = Field(default_factory=list)
    uncited_claims: list[str] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    disclaimer_present: bool = True
    notes: list[str] = Field(default_factory=list)


class ResearchReport(BaseModel):
    """The full report. Prose is generated; every fact traces to the decision."""

    ticker: str
    company_name: str
    as_of: str | None = None
    generated_at: str | None = None

    executive_summary: list[str] = Field(default_factory=list)
    rating_rationale: str = ""           # explains the FIXED rating; cannot set it
    investment_view: InvestmentView = Field(default_factory=InvestmentView)
    what_would_change_our_view: WhatWouldChangeView = Field(default_factory=WhatWouldChangeView)
    analyst_caveat: str | None = None    # E8: disagreement with the score is surfaced here

    sections: list[ReportSection] = Field(default_factory=list)
    citations: list[str] = Field(default_factory=list)

    decision: InvestmentDecision         # the fixed rating/score/valuation — the source of truth
    verification: VerificationResult | None = None
    unverified_banner: bool = False      # set when verification failed twice (PRD 8.13, veto V9)
    disclaimer: str = ""


# The mandatory disclaimer, verbatim from PRD 20.2. Never abbreviated.
DISCLAIMER_TEMPLATE = (
    "DISCLAIMER — EDUCATIONAL AND ACADEMIC USE ONLY\n\n"
    "This report is generated by an automated academic research system built as "
    "a postgraduate management project. It is not investment advice, not a "
    "recommendation to buy, sell or hold any security, and not a research report "
    "issued by a SEBI-registered Research Analyst or Investment Adviser.\n\n"
    "The analysis is impersonal and does not consider the financial situation, "
    "investment objectives or risk tolerance of any person. Data is sourced from "
    "third-party providers and may be incomplete, delayed or inaccurate. "
    "Valuation outputs depend materially on assumptions that are inherently "
    "uncertain. Parts of this report are generated by a large language model and "
    "may contain errors despite automated verification.\n\n"
    "Nothing here should be relied upon for any investment decision. Consult a "
    "SEBI-registered investment adviser before investing. The author accepts no "
    "liability for any loss arising from use of this output.\n\n"
    "Data as of: {data_as_of} · Report generated: {generated_at} · "
    "Config version: weights {weights_version} / thresholds {thresholds_version} / "
    "valuation {valuation_version}"
)


def build_disclaimer(decision: InvestmentDecision, *, data_as_of: str | None,
                     generated_at: str | None) -> str:
    """The stamped disclaimer for one report (PRD 20.2)."""
    return DISCLAIMER_TEMPLATE.format(
        data_as_of=data_as_of or "n/a",
        generated_at=generated_at or "n/a",
        weights_version=decision.weights_version or "?",
        thresholds_version=decision.thresholds_version or "?",
        valuation_version=decision.valuation_version or "?",
    )
